### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by oovillagran** [oovillagran/space_travelers#25]
This is our React Group Project - Space Travelers Hub. The team members are:
- @LarryIVC.
- @flemton.
- @oovillagran .

We are three members in our team.

This is the link for our project:
https://github.com/oovillagran/space_travelers/projects/1

**Comment by DuaneDave** [comment]
Hi @oovillagran , @flemton and @LarryIVC  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ The kanban board is set up correctly

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
